import { describe, expect, it } from 'vitest';
import { itemCatalog } from '$lib/catalogs/items';
import { ticketTemplates } from '$lib/catalogs/tickets';
import { playerTitle, shopFlavorForLevel, titleForLevel } from '$lib/catalogs/titles';
import { activateProducer, applyLevel, cashoutExpiredHackathon, cashoutExpiredRetro, catalogErrors, checkLevel, completeTicket, createGame, discardItem, energyPurchaseQuote, expandRack, findMergeHint, findProducerHint, itemsContributingToTicket, itemsForTicket, hackathonCashoutQuote, moveGenerator, moveOrMerge, normalizeEnergy, purchaseEnergy, rackExpansionQuote, rackItemSize, rackUsed, reassignTicket, redeemEventItem, repairSaveShape, repairTicketQueue, retrieveFromRack, storeInRack, syncProgressionUnlocks, ticketReady, ticketReassignmentQuote, tidyBoard, tidyQuote, validateState, weightedDrop } from './game';

describe('catalog and initial state',()=>{
  it('has continuous, unique definitions',()=>expect(catalogErrors()).toEqual([]));
  it('has ticket coverage for every permanent merge-chain item',()=>{
    const covered=new Set(ticketTemplates.flatMap(template=>template.requirements.map(requirement=>requirement.itemId)));
    const uncovered=itemCatalog.filter(item=>item.kind==='mergeable'&&!['hackathon','retro'].includes(item.chainId??'')&&!covered.has(item.id)).map(item=>item.id);
    expect(uncovered).toEqual([]);
  });
  it('creates a valid board and three different tickets',()=>{const state=createGame(1000);expect(state.cells).toHaveLength(63);expect(state.tickets).toHaveLength(3);expect(new Set(state.tickets.map(ticket=>ticket.title)).size).toBe(3);expect(validateState(state)).toEqual([])});
  it('repairs duplicate tickets from an existing save',()=>{const state=createGame(1000);state.tickets=[state.tickets[0],structuredClone(state.tickets[0]),structuredClone(state.tickets[0])];expect(repairTicketQueue(state,2000)).toBe(true);expect(new Set(state.tickets.map(ticket=>ticket.title)).size).toBe(3)});
});
describe('titles and promotion',()=>{
  it('assigns the starting title to new games',()=>{const state=createGame(0);expect(state.player.title).toBe('Intern')});
  it('repairs missing titles from old saves',()=>{const state=createGame(0);delete (state.player as {title?:string}).title;expect(repairSaveShape(state)).toBe(true);expect(state.player.title).toBe('Intern')});
  it('migrates old saves to schema 6 with rack, services, hint, and appearance settings',()=>{const state=createGame(0);state.schemaVersion=2;delete (state as Partial<typeof state>).achievements;delete (state as Partial<typeof state>).statistics;delete (state as Partial<typeof state>).serverRack;delete (state as Partial<typeof state>).tidyService;delete (state as Partial<typeof state>).ticketReassignment;delete (state.settings as Partial<typeof state.settings>).hints;delete (state.settings as Partial<typeof state.settings>).appearance;expect(repairSaveShape(state)).toBe(true);expect(state.schemaVersion).toBe(6);expect(state.settings.hints).toBe(true);expect(state.settings.appearance).toBe('dark');expect(state.achievements).toEqual({});expect(state.statistics).toEqual({mergesCompleted:0,ticketsCompleted:0,eventFinalsRedeemed:0});expect(state.serverRack).toEqual({capacity:6,expansions:0,items:[]});expect(state.tidyService).toEqual({windowStartedAt:null,uses:0});expect(state.ticketReassignment).toEqual({windowStartedAt:null,uses:0})});
  it('promotes through the startup ladder by level',()=>{expect(playerTitle(1)).toBe('Intern');expect(playerTitle(5)).toBe('Code Monkey');expect(playerTitle(30)).toBe('10x Engineer');expect(playerTitle(100)).toBe('Platform Legend');expect(playerTitle(230)).toBe('Angel Investor');expect(playerTitle(450)).toBe('Shadow CTO')});
  it('reports promotion when a title threshold is crossed',()=>{const state=createGame(0);state.player.xp=400;state.player.level=4;state.player.title=playerTitle(4);state.player.energy=10;const result=applyLevel(state);expect(result.promoted).toBe(true);expect(result.newTitle).toBe('Code Monkey')});
  it('refills energy on promotion',()=>{const state=createGame(0);state.player.xp=400;state.player.level=4;state.player.title=playerTitle(4);state.player.energy=10;applyLevel(state);expect(state.player.energy).toBe(state.player.maxEnergy)});
  it('does not refill energy on a plain level gain',()=>{const state=createGame(0);state.player.xp=150;state.player.level=1;state.player.title='Intern';state.player.energy=10;const result=applyLevel(state);expect(result.promoted).toBe(false);expect(state.player.energy).toBe(10)});
  it('does not report promotion when only the level number changes',()=>{const state=createGame(0);state.player.xp=150;state.player.level=1;state.player.title='Intern';const result=applyLevel(state);expect(result.promoted).toBe(false);expect(result.newLevel).toBe(2)});
  it('provides a shop flavor for every defined tier',()=>{for(const tier of [1,5,10,15,20,25,30,40,50,65,80,100,125,155,190,230,275,325,385,450])expect(shopFlavorForLevel(tier).length).toBeGreaterThan(0)});
});
describe('energy and spawning',()=>{
  it('normalizes elapsed time and clamps at maximum',()=>{const state=createGame(0);state.player.energy=90;normalizeEnergy(state,30*120_000);expect(state.player.energy).toBe(100)});
  it('does not dirty an idle full energy bar',()=>{const state=createGame(0);expect(normalizeEnergy(state,120_000)).toBe(false);expect(state.player.energyUpdatedAt).toBe(0)});
  it('selects weighted boundaries and ignores invalid weights',()=>{const choices=[{id:'a',weight:3},{id:'bad',weight:0},{id:'b',weight:1}];expect(weightedDrop(choices,()=>0)?.id).toBe('a');expect(weightedDrop(choices,()=>.999)?.id).toBe('b')});
  it('spends energy only after a successful spawn',()=>{const state=createGame(0),producer=state.items[0];const result=activateProducer(state,producer.instanceId,()=>0,1);expect(result.ok).toBe(true);expect(result.state.player.energy).toBe(99);expect(result.state.items.some(i=>i.definitionId==='character')).toBe(true)});
  it('does not spend energy when production is blocked by a full board',()=>{const state=createGame(0),producer=state.items[0];state.cells.filter(cell=>!cell.locked&&cell.index!==producer.cellIndex).forEach((cell,index)=>state.items.push({instanceId:`full-${index}`,definitionId:'character',cellIndex:cell.index,createdAt:1}));const result=activateProducer(state,producer.instanceId,()=>0,2);expect(result.ok).toBe(false);expect(result.reason).toContain('No free cells');expect(result.state.player.energy).toBe(100)});
  it('unlocks the infrastructure producer at level 7 with its own drops and cost',()=>{const state=createGame(0);state.player.level=6;expect(syncProgressionUnlocks(state,1)).toBe(false);state.player.level=7;expect(syncProgressionUnlocks(state,2)).toBe(true);const producer=state.items.find(item=>item.definitionId==='infrastructure_workbench');expect(producer).toBeDefined();const result=activateProducer(state,producer!.instanceId,()=>0,3);expect(result.ok).toBe(true);expect(result.state.player.energy).toBe(98);expect(result.state.items.some(item=>item.definitionId==='raspberry_pi')).toBe(true)});
  it('unlocks the HTML Workbench at level 20 and renders its own chain',()=>{const state=createGame(0);state.player.level=19;syncProgressionUnlocks(state,1);expect(state.items.some(item=>item.definitionId==='html_workbench')).toBe(false);state.player.level=20;expect(syncProgressionUnlocks(state,2)).toBe(true);const producer=state.items.find(item=>item.definitionId==='html_workbench')!;expect(state.achievements['html-operator']).toBeDefined();const result=activateProducer(state,producer.instanceId,()=>0,3);expect(result.ok).toBe(true);expect(result.state.player.energy).toBe(97);expect(result.state.items.some(item=>item.definitionId==='angle_bracket')).toBe(true)});
  it('unlocks the CSS Selector Lab at level 27 with a distinct nine-level chain',()=>{const state=createGame(0);state.player.level=26;syncProgressionUnlocks(state,1);expect(state.items.some(item=>item.definitionId==='css_selector_lab')).toBe(false);state.player.level=27;expect(syncProgressionUnlocks(state,2)).toBe(true);const producer=state.items.find(item=>item.definitionId==='css_selector_lab')!;expect(state.achievements['css-operator']).toBeDefined();const result=activateProducer(state,producer.instanceId,()=>0,3);expect(result.ok).toBe(true);expect(result.state.player.energy).toBe(97);expect(result.state.items.some(item=>item.definitionId==='type_selector')).toBe(true);expect(itemCatalog.filter(item=>item.chainId==='css')).toHaveLength(9)});
  it('occasionally produces regressions from the CSS Selector Lab',()=>{const state=createGame(0);state.player.level=27;syncProgressionUnlocks(state,1);const producer=state.items.find(item=>item.definitionId==='css_selector_lab')!;const result=activateProducer(state,producer.instanceId,()=>0.999,2);expect(result.state.items.some(item=>item.definitionId==='regression')).toBe(true)});
  it('deploys Retro Computing Week at level 14 and cools down after a seven-item burst',()=>{const start=Date.parse('2026-08-07T12:00:00-04:00');let state=createGame(start);state.player.level=14;state.cells.forEach(cell=>{cell.locked=false;cell.unlockCost=undefined});expect(syncProgressionUnlocks(state,start)).toBe(true);const producer=state.items.find(item=>item.definitionId==='event_pipeline')!;expect(producer.state?.activationsRemaining).toBe(7);for(let index=0;index<7;index++){const result=activateProducer(state,producer.instanceId,()=>0,start+index);expect(result.ok).toBe(true);state=result.state}const cooling=state.items.find(item=>item.instanceId===producer.instanceId)!;expect(cooling.state?.activationsRemaining).toBe(0);expect(activateProducer(state,producer.instanceId,()=>0,start+7).reason).toContain('cooling down');const recharged=activateProducer(state,producer.instanceId,()=>0,start+12*60*1000+10);expect(recharged.ok).toBe(true);expect(recharged.state.items.find(item=>item.instanceId===producer.instanceId)?.state?.activationsRemaining).toBe(6)});
  it('hides the seasonal generator before and after its active event',()=>{const state=createGame(0);state.player.level=14;syncProgressionUnlocks(state,Date.parse('2026-08-06T12:00:00-04:00'));expect(state.items.some(item=>item.definitionId==='event_pipeline')).toBe(false);syncProgressionUnlocks(state,Date.parse('2026-08-07T12:00:00-04:00'));expect(state.items.some(item=>item.definitionId==='event_pipeline')).toBe(true);syncProgressionUnlocks(state,Date.parse('2026-08-15T00:00:00-04:00'));expect(state.items.some(item=>item.definitionId==='event_pipeline')).toBe(false)});
});
describe('board commands',()=>{
  it('moves, swaps, and merges without duplicate occupancy',()=>{let state=createGame(0);state.items.push({instanceId:'a',definitionId:'character',cellIndex:0,createdAt:1},{instanceId:'b',definitionId:'character',cellIndex:1,createdAt:2},{instanceId:'c',definitionId:'typo',cellIndex:2,createdAt:3});let result=moveOrMerge(state,'c',4);expect(result.action).toBe('move');result=moveOrMerge(result.state,'c',0);expect(result.action).toBe('swap');result=moveOrMerge(result.state,'a',1);expect(result.action).toBe('merge');expect(result.state.items.some(i=>i.definitionId==='string')).toBe(true);expect(validateState(result.state)).toEqual([])});
  it('awards and persists the first merge badge',()=>{const state=createGame(0);state.items.push({instanceId:'a',definitionId:'character',cellIndex:0,createdAt:1},{instanceId:'b',definitionId:'character',cellIndex:1,createdAt:2});const result=moveOrMerge(state,'a',1,10);expect(result.state.statistics.mergesCompleted).toBe(1);expect(result.state.achievements['first-merge']).toEqual({earnedAt:10})});
  it('rejects locked cells without mutation',()=>{const state=createGame(0);state.items.push({instanceId:'a',definitionId:'character',cellIndex:0,createdAt:1});const result=moveOrMerge(state,'a',62);expect(result.ok).toBe(false);expect(state.items.at(-1)?.cellIndex).toBe(0)});
  it('moves generators only to empty unlocked cells and preserves their operating state',()=>{const state=createGame(0),producer=state.items.find(item=>item.definitionId==='workstation')!;producer.state={activationsRemaining:2,cooldownUntil:500};const moved=moveGenerator(state,producer.instanceId,8,10);expect(moved.ok).toBe(true);expect(moved.state.items.find(item=>item.instanceId===producer.instanceId)).toMatchObject({cellIndex:8,state:{activationsRemaining:2,cooldownUntil:500}});expect(producer.cellIndex).toBe(3);expect(moveGenerator(moved.state,producer.instanceId,62,11).ok).toBe(false);moved.state.items.push({instanceId:'occupied',definitionId:'character',cellIndex:9,createdAt:1});expect(moveGenerator(moved.state,producer.instanceId,9,12).ok).toBe(false)});
  it('finds the first mergeable pair but ignores top-level duplicates',()=>{const state=createGame(0);state.items.push({instanceId:'top-a',definitionId:'application',cellIndex:0,createdAt:1},{instanceId:'top-b',definitionId:'application',cellIndex:1,createdAt:1},{instanceId:'pair-a',definitionId:'character',cellIndex:8,createdAt:1},{instanceId:'pair-b',definitionId:'character',cellIndex:9,createdAt:1});expect(findMergeHint(state)).toEqual(['pair-a','pair-b'])});
  it('hints a usable producer that can build a missing ticket requirement',()=>{const state=createGame(0);state.player.level=27;syncProgressionUnlocks(state,1);state.tickets[0].requirements=[{itemId:'design_system',quantity:1}];const css=state.items.find(item=>item.definitionId==='css_selector_lab')!;expect(findProducerHint(state,2)).toBe(css.instanceId)});
  it('does not hint a producer when production cannot use a free cell',()=>{const state=createGame(0);const occupied=new Set(state.items.map(item=>item.cellIndex));state.cells.filter(cell=>!cell.locked&&!occupied.has(cell.index)).forEach((cell,index)=>state.items.push({instanceId:`block-${index}`,definitionId:'application',cellIndex:cell.index,createdAt:1}));expect(findProducerHint(state,2)).toBeUndefined()});
  it('discards low levels and salvages higher workstation and infrastructure items',()=>{const state=createGame(0);state.player.energy=50;state.items.push({instanceId:'low',definitionId:'character',cellIndex:0,createdAt:1,originProducerId:'workstation'},{instanceId:'code',definitionId:'function',cellIndex:1,createdAt:1,originProducerId:'workstation'},{instanceId:'server',definitionId:'rack_server',cellIndex:2,createdAt:1,originProducerId:'infrastructure_workbench'});let result=discardItem(state,'low',2);expect(result.state.player.energy).toBe(50);result=discardItem(result.state,'code',3);expect(result.state.player.energy).toBe(54);result=discardItem(result.state,'server',4);expect(result.state.player.credits).toBe(125)});
  it('tidies mergeables from low to high without moving producers',()=>{const state=createGame(0);state.player.credits=500;state.items.push({instanceId:'high',definitionId:'function',cellIndex:20,createdAt:1},{instanceId:'low',definitionId:'character',cellIndex:30,createdAt:2});const result=tidyBoard(state,3);expect(result.ok).toBe(true);expect(result.state.player.credits).toBe(250);expect(result.state.items.find(item=>item.instanceId==='low')?.cellIndex).toBe(0);expect(result.state.items.find(item=>item.instanceId==='high')?.cellIndex).toBe(1);expect(result.state.items.find(item=>item.definitionId==='workstation')?.cellIndex).toBe(3)});
  it('doubles Tidy pricing within six hours and resets afterward',()=>{let state=createGame(0);state.player.credits=10_000;expect(tidyQuote(state,1).cost).toBe(250);let result=tidyBoard(state,1);expect(result.state.player.credits).toBe(9_750);state=result.state;expect(tidyQuote(state,2).cost).toBe(500);result=tidyBoard(state,2);expect(result.state.player.credits).toBe(9_250);expect(tidyQuote(result.state,6*60*60*1000+2).cost).toBe(250)});
  it('stores items by U size and excludes them from ticket delivery until returned',()=>{const state=createGame(0);state.player.level=18;state.items.push({instanceId:'small',definitionId:'character',cellIndex:0,createdAt:1},{instanceId:'medium',definitionId:'function',cellIndex:1,createdAt:1});state.tickets[0].requirements=[{itemId:'function',quantity:1}];expect(rackItemSize('character')).toBe(1);expect(rackItemSize('function')).toBe(2);let result=storeInRack(state,'medium',2);expect(result.ok).toBe(true);expect(rackUsed(result.state)).toBe(2);expect(ticketReady(result.state,result.state.tickets[0])).toBe(false);expect(result.state.achievements['rack-mounted']).toBeDefined();result=retrieveFromRack(result.state,'medium',3);expect(result.ok).toBe(true);expect(rackUsed(result.state)).toBe(0);expect(ticketReady(result.state,result.state.tickets[0])).toBe(true)});
  it('blocks oversized storage and expands the rack on a rising permanent price curve',()=>{let state=createGame(0);state.player.level=18;state.player.credits=2_000;for(let index=0;index<2;index++)state.items.push({instanceId:`large-${index}`,definitionId:'cloud_region',cellIndex:index,createdAt:1});let result=storeInRack(state,'large-0',2);expect(result.ok).toBe(true);result=storeInRack(result.state,'large-1',3);expect(result.ok).toBe(true);expect(rackUsed(result.state)).toBe(6);state=result.state;state.items.push({instanceId:'extra',definitionId:'character',cellIndex:2,createdAt:1});expect(storeInRack(state,'extra',4).ok).toBe(false);expect(rackExpansionQuote(state).cost).toBe(250);result=expandRack(state,5);expect(result.state.serverRack.capacity).toBe(9);expect(result.state.player.credits).toBe(1_750);expect(rackExpansionQuote(result.state).cost).toBe(500)});
  it('mounts a generator in 4U without progression redeploying it',()=>{const now=Date.parse('2026-08-08T12:00:00-04:00'),state=createGame(now);state.player.level=18;syncProgressionUnlocks(state,now);const producer=state.items.find(item=>item.definitionId==='infrastructure_workbench')!;expect(rackItemSize(producer.definitionId)).toBe(4);const result=storeInRack(state,producer.instanceId,now);expect(result.ok).toBe(true);expect(result.state.items.some(item=>item.definitionId==='infrastructure_workbench')).toBe(false);expect(syncProgressionUnlocks(result.state,now+1)).toBe(false);expect(result.state.serverRack.items.some(item=>item.definitionId==='infrastructure_workbench')).toBe(true)});
});
describe('tickets',()=>{
  it('consumes deterministically and grants rewards atomically',()=>{const state=createGame(0),ticket=state.tickets[0];for(const requirement of ticket.requirements)for(let n=0;n<requirement.quantity;n++)state.items.push({instanceId:`${requirement.itemId}-${n}`,definitionId:requirement.itemId,cellIndex:10+n,createdAt:n});expect(ticketReady(state,ticket)).toBe(true);const result=completeTicket(state,ticket.id,10);expect(result.ok).toBe(true);expect(result.state.tickets).toHaveLength(3);expect(result.state.player.credits).toBeGreaterThan(state.player.credits);expect(result.state.statistics.ticketsCompleted).toBe(1);expect(result.state.achievements['first-ticket']).toEqual({earnedAt:10})});
  it('does nothing when requirements are absent',()=>{const state=createGame(0),before=structuredClone(state);const result=completeTicket(state,state.tickets[0].id,10);expect(result.ok).toBe(false);expect(state).toEqual(before)});
  it('identifies the exact lowest-cell items reserved for a ready ticket',()=>{const state=createGame(0),ticket=state.tickets[0],requirement=ticket.requirements[0];state.items.push({instanceId:'later-cell',definitionId:requirement.itemId,cellIndex:12,createdAt:1},{instanceId:'first-cell',definitionId:requirement.itemId,cellIndex:8,createdAt:2});const reserved=itemsForTicket(state,ticket);expect(reserved).toHaveLength(requirement.quantity);expect(reserved[0].instanceId).toBe('first-cell')});
  it('highlights available contributors before the whole ticket is ready',()=>{const state=createGame(0),ticket=state.tickets[0];ticket.requirements=[{itemId:'character',quantity:1},{itemId:'function',quantity:1}];state.items.push({instanceId:'partial',definitionId:'character',cellIndex:8,createdAt:1});expect(ticketReady(state,ticket)).toBe(false);expect(itemsForTicket(state,ticket)).toEqual([]);expect(itemsContributingToTicket(state,ticket).map(item=>item.instanceId)).toEqual(['partial'])});
  it('reassigns in place, charges credits, and never immediately repeats the rejected ticket',()=>{const state=createGame(0);state.player.credits=2_000;const rejected=state.tickets[0],otherIds=state.tickets.slice(1).map(ticket=>ticket.id);const result=reassignTicket(state,rejected.id,10);expect(result.ok).toBe(true);expect(result.state.player.credits).toBe(1_900);expect(result.state.tickets).toHaveLength(3);expect(result.state.tickets[0].title).not.toBe(rejected.title);expect(result.state.tickets.slice(1).map(ticket=>ticket.id)).toEqual(otherIds);expect(result.state.ticketReassignment).toEqual({windowStartedAt:10,uses:1,lastRejectedTitle:rejected.title})});
  it('doubles reassignment pricing for six hours and resets without mutating an unaffordable save',()=>{let state=createGame(0);state.player.credits=2_000;state=reassignTicket(state,state.tickets[0].id,1).state;expect(ticketReassignmentQuote(state,2).cost).toBe(200);state=reassignTicket(state,state.tickets[0].id,2).state;expect(ticketReassignmentQuote(state,3).cost).toBe(400);expect(ticketReassignmentQuote(state,6*60*60*1000+2).cost).toBe(100);state.player.credits=0;const before=structuredClone(state),failed=reassignTicket(state,state.tickets[0].id,3);expect(failed.ok).toBe(false);expect(state).toEqual(before)});
});
describe('energy economy',()=>{
  it('cashes out all expired Hackathon items at level-scaled credit values',()=>{const state=createGame(0);state.items.push({instanceId:'drink',definitionId:'energy_drink',cellIndex:8,createdAt:1},{instanceId:'trophy',definitionId:'winning_hack',cellIndex:9,createdAt:1});expect(hackathonCashoutQuote(state)).toEqual({items:2,credits:510});const result=cashoutExpiredHackathon(state,Date.parse('2026-07-27T12:00:00-04:00'));expect(result.ok).toBe(true);expect(result.state.player.credits).toBe(610);expect(result.state.items.some(item=>item.definitionId==='energy_drink'||item.definitionId==='winning_hack')).toBe(false)});
  it('includes stored event items in the expired-event cashout',()=>{let state=createGame(0);state.player.level=18;state.items.push({instanceId:'stored-drink',definitionId:'energy_drink',cellIndex:8,createdAt:1});state=storeInRack(state,'stored-drink',2).state;expect(hackathonCashoutQuote(state)).toEqual({items:1,credits:10});const result=cashoutExpiredHackathon(state,Date.parse('2026-07-27T12:00:00-04:00'));expect(result.ok).toBe(true);expect(result.state.serverRack.items).toEqual([])});
  it('archives retro event items for credits after the event',()=>{const state=createGame(0);state.items.push({instanceId:'disk',definitionId:'floppy_disk',cellIndex:8,createdAt:1});const result=cashoutExpiredRetro(state,Date.parse('2026-08-15T00:00:00-04:00'));expect(result.ok).toBe(true);expect(result.state.player.credits).toBe(155);expect(result.state.items.some(item=>item.definitionId==='floppy_disk')).toBe(false)});
  it('trades a Winning Hack for the selected event reward',()=>{const state=createGame(0);state.player.energy=20;state.items.push({instanceId:'winner',definitionId:'winning_hack',cellIndex:8,createdAt:1});const energy=redeemEventItem(state,'winner','energy',2);expect(energy.ok).toBe(true);expect(energy.state.player.energy).toBe(70);expect(energy.state.items.some(item=>item.instanceId==='winner')).toBe(false);const creditState=structuredClone(state);const credits=redeemEventItem(creditState,'winner','credits',2);expect(credits.state.player.credits).toBe(state.player.credits+500)});
  it('does not consume a winning hack when energy is already full',()=>{const state=createGame(0);state.items.push({instanceId:'winner',definitionId:'winning_hack',cellIndex:8,createdAt:1});const result=redeemEventItem(state,'winner','energy',2);expect(result.ok).toBe(false);expect(result.state.items.some(item=>item.instanceId==='winner')).toBe(true)});
  it('scales recharge prices and resets them after six hours',()=>{let state=createGame(0);state.player.energy=0;state.player.credits=10_000;let result=purchaseEnergy(state,1);expect(result.ok).toBe(true);expect(result.state.player.credits).toBe(9_800);state=result.state;state.player.energy=0;expect(energyPurchaseQuote(state,2).cost).toBe(400);const afterWindow=6*60*60*1000+2;state.player.energyUpdatedAt=afterWindow;result=purchaseEnergy(state,afterWindow);expect(result.ok).toBe(true);expect(result.state.player.credits).toBe(9_600)});
  it('halves recharge cost after the full board is unlocked',()=>{const state=createGame(0);state.player.energy=0;state.cells.forEach(cell=>cell.locked=false);expect(energyPurchaseQuote(state,1).cost).toBe(100)});
  it('returns ticket energy without exceeding capacity',()=>{const state=createGame(0),ticket=state.tickets[0];ticket.rewards.energy=2;state.player.energy=99;for(const req of ticket.requirements)for(let n=0;n<req.quantity;n++)state.items.push({instanceId:`reward-${req.itemId}-${n}`,definitionId:req.itemId,cellIndex:10+n,createdAt:n});const result=completeTicket(state,ticket.id,1);expect(result.state.player.energy).toBe(100)});
});
